// <auto-generated />
namespace SmlGround.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SocialDB2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SocialDB2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811061407358_SocialDB2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
