// <auto-generated />
namespace SmlGround.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SocialDB27111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SocialDB27111));
        
        string IMigrationMetadata.Id
        {
            get { return "201811271335566_SocialDB 27.111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
