// <auto-generated />
namespace SmlGround.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SocialDb1309 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SocialDb1309));
        
        string IMigrationMetadata.Id
        {
            get { return "201901031304190_SocialDb 13.09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
