// <auto-generated />
namespace SmlGround.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SocialDb1209 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SocialDb1209));
        
        string IMigrationMetadata.Id
        {
            get { return "201901030922148_SocialDb 12.09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
